#!/bin/sh

targ='/usr/bin'

#-
#-[usage]
#-	ws start
#-	ws stop
#-	ws list
#-	ws env
#-	ws ln
#-

usage()
{
	cat `which ws` | grep '#-' | grep -v grep | sed 's/#-//g'
}


case "$1" in
start)
	sudo pm2 start ecosystem.config.js
	;;
stop)
	sudo pm2 stop ecosystem.config.js
	;;
list)
	sudo pm2 list
	;;
env)
	ls -l $targ/* | grep nvm
	;;
ln)
	for b in `echo node pm2`
	do
		echo "sudo ln -s $(which $b) $targ/$b"
	done
	;;
*)
	usage
	;;
esac

