#!/bin/sh

targ='/usr/bin'

# [NOTE] deploy as /usr/local/sbin/ws


case "$1" in
start)
	sudo pm2 start ecosystem.config.js
	;;
stop)
	sudo pm2 stop ecosystem.config.js
	;;
list)
	sudo pm2 list
	;;
env)
	ls -l $targ/* | grep nvm
	;;
ln)
	for b in `echo node pm2`
	do
		echo "sudo ln -s $(which $b) $targ/$b"
	done
	;;
esac
